//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Marketing = new HashSet<Marketing>();
            this.Publicidad = new HashSet<Publicidad>();
            this.Recordatorio = new HashSet<Recordatorio>();
            this.ServicioEmpresa = new HashSet<ServicioEmpresa>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id_Empresa { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre de la empresa")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Ingrese el correo de la empresa")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }
        [DisplayName("Identificación")]
        [RegularExpression(@"[0-9]{1,9}(\.[0-9]{0,2})?$", ErrorMessage = "El largo de la cédula no es correcta")]
        [Required(ErrorMessage = "Ingrese la cédula de la empresa")]
        public string Cedula { get; set; }
        [Required(ErrorMessage = "Ingrese el país de la empresa")]
        public Nullable<int> Id_Pais { get; set; }
        public Nullable<int> Id_Provincia { get; set; }
        public Nullable<int> Id_Canton { get; set; }
        public Nullable<int> Id_Distrito { get; set; }
        [DisplayName("Otras Señas")]
        [Required(ErrorMessage = "Ingrese el campo otras señas")]
        public string Otras_Señas { get; set; }
        [DisplayName("Codigo Postal")]
        [RegularExpression(@"[0-9]{1,9}(\.[0-9]{0,2})?$", ErrorMessage = "Solamente se permiten números enteros")]
        public int Codigo_Postal { get; set; }
        [DisplayName("Tipo Cedula")]
        [Required(ErrorMessage = "Seleccione el tipo de cédula")]
        public string Tipo_Cedula { get; set; }
    
        public virtual Canton Canton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual EstadodeCuenta EstadodeCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marketing> Marketing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicidad> Publicidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recordatorio> Recordatorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioEmpresa> ServicioEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
