//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int Id_Usuario { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre del usuario")]
        public string Nombre { get; set; }
        
        [DisplayName("1º Apellido")]
        
        [Required(ErrorMessage = "Ingrese el Apellido1 del usuario")]
        public string Apellido1 { get; set; }
        [DisplayName("2º Apellido")]
        [Required(ErrorMessage = "Ingrese el correo del usuario")]
        public string Apellido2 { get; set; }
        [Required(ErrorMessage = "Ingrese el correo del usuario")]
        public string Correo { get; set; }
        [Required(ErrorMessage = "Ingrese la contraseña del usuario")]
        public string Contraseña { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha Creación")]
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Rol { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
