
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace C_R_M.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contacto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contacto()
    {

        this.Correo = new HashSet<Correo>();

        this.Telefono = new HashSet<Telefono>();

    }


    public int Id_Contacto { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre del contacto")]

        public string Nombre { get; set; }
        [Required(ErrorMessage = "Ingrese el primer apellido del contacto")]

        public string Apellido1 { get; set; }
        [Required(ErrorMessage = "Ingrese el segundo apellido del contacto")]

        public string Apellido2 { get; set; }

    public string Puesto { get; set; }

    public Nullable<int> Empresa { get; set; }



    public virtual Empresa Empresa1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Correo> Correo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Telefono> Telefono { get; set; }

}

}
