
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace C_R_M.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cuenta
{

    public int Id_Cuenta { get; set; }
        [Required(ErrorMessage = "Indique la empresa")]

        public int Servicio_Empresa { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Fecha_Pago { get; set; }

    public double Monto_Abono { get; set; }

    public Nullable<double> Monto_Pendiente { get; set; }

    public string Descripcion { get; set; }



    public virtual ServicioEmpresa ServicioEmpresa { get; set; }

}

}
