
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace C_R_M.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class EstadodeCuenta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EstadodeCuenta()
    {

        this.Publicidad = new HashSet<Publicidad>();

    }


    public int Id_Estado { get; set; }
        [Required(ErrorMessage = "Indique la empresa")]
        public Nullable<int> Id_Credito_Disponible { get; set; }
        [Required(ErrorMessage = "Indique la empresa")]
        public Nullable<int> Empresa { get; set; }



    public virtual Empresa Empresa1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Publicidad> Publicidad { get; set; }

}

}
