
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace C_R_M.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Movimiento
{

    public int Id_Movimiento { get; set; }
        [Required(ErrorMessage = "Indique el tipo")]
        public string Tipo { get; set; }
        [Required(ErrorMessage = "Ingrese el Monto")]

        [RegularExpression(@"[0-9]{1,9}(\.[0-9]{0,2})?$", ErrorMessage = "Solamente se permiten números")]
        public Nullable<double> Monto { get; set; }
        [DataType(DataType.MultilineText)]
        public string Detalle { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha { get; set; }

}

}
