
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace C_R_M.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Producto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Producto()
    {

        this.Marketing = new HashSet<Marketing>();

        this.Marketing1 = new HashSet<Marketing>();

        this.ServicioEmpresa = new HashSet<ServicioEmpresa>();

    }


    public int Id_Producto { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre del producto")]
        public string Nombre { get; set; }

    public string Codigo { get; set; }
        [Required(ErrorMessage = "Indique el tipo")]
        public string Tipo_Producto { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Marketing> Marketing { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Marketing> Marketing1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ServicioEmpresa> ServicioEmpresa { get; set; }

}

}
