//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_R_M.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Telefono
    {
        public int Id_Telefono { get; set; }
        [Required(ErrorMessage = "Ingrese el nombre de la empresa")]
        [RegularExpression(@"[0-9]{1,9}(\.[0-9]{0,2})?$", ErrorMessage = "Solamente se permiten números enteros")]
        public Nullable<int> Telefono1 { get; set; }
        public Nullable<int> Contacto { get; set; }
    
        public virtual Contacto Contacto1 { get; set; }
    }
}
